### ISSUE TITLE
RNG types are not public

### ISSUE THREAD

**Issue by PaulMaynard** [alexschrod/doryen-extra#1]
When I try to use the `Random` struct, I can't acess the `MersenneTwister` and `ComplementaryMultiplyWithCarry` types because they are private.

**Comment by ilyvion** [comment]
Sorry about the slow response, I've been a little busy these last few days.

That was kind of done on purpose; I'm sorry that the documentation isn't quite up to snuff yet, but the way you are meant to use `Random` is by either using a generic type parameter, i.e.
```rust
use doryen_extra::random::{Algorithm, Random};
fn use_random<A: Algorithm>(random: Random<A>) {
    unimplemented!()
}

fn main() {
    let random = Random::new_mt();
    use_random(random);
}
```
or, by using the `Rng` trait:
```rust
use doryen_extra::random::{Algorithm, Random, Rng};
fn use_random<R: Rng>(rng: R) {
    unimplemented!()
}

fn main() {
    let random = Random::new_mt();
    use_random(random);
}
```

Feel free to let me know if that's not good enough, I'll see what I can do.
